### ISSUE TITLE
Distribution charts not rendering

### ISSUE THREAD

**Issue by bruth** [chop-dbhi/cilantro#773]
This was observed as of 7f65fba63536cb1b0f8188875144b15d7070fac0.

<img width="740" alt="screen shot 2015-11-15 at 9 50 32 am" src="https://cloud.githubusercontent.com/assets/515142/11169186/78a498cc-8b7e-11e5-8aea-0bd0f7f183f0.png">

**Comment by naegelyd** [comment]
Looking into this now but I'm not certain it is related to https://github.com/chop-dbhi/cilantro/pull/772. Testing locally, the distribution chart does not render correctly on 120f7e13e8f93f8e2b97ba2ae733934a46ad2657 either.

**Comment by naegelyd** [comment]
Whatever is causing this does not seem to affect all distribution charts. For example, the age chart renders just fine and it is a distribution chart.

![screen shot 2015-11-15 at 12 23 37 pm](https://cloud.githubusercontent.com/assets/3911912/11170795/e3f0165a-8b93-11e5-9600-de1aa6c70dcf.png)

**Comment by naegelyd** [comment]
Seems like this might be affecting all the numeric data. `Mean Corpuscular Volume (MCV)` and `White Blood Cells (WBC)` also fail to render with a blank chart just like `Hemoglobin (HGB)`

**Comment by naegelyd** [comment]
So, after looking at this further, this seems to be an issue in highcharts which is being encountered due to a change in our dist endpoint. First, let's consider the difference in our endpoint then we can look at highcharts. 

#### [resources/field/dist.py](https://github.com/chop-dbhi/serrano/blob/master/serrano/resources/field/dist.py)
In [this commit])https://github.com/chop-dbhi/serrano/commit/4f005a253732762856e44bb08a527bd9e41854c6#diff-021a7c72a335c929a94b4de4d5055630), the dist endpoint was updated to use the `DataField.dist` method. As a result, the ordering of the returned data changed. Here is a comparison of the data returned data before and after.

__Before__
![screen shot 2015-11-15 at 2 28 20 pm](https://cloud.githubusercontent.com/assets/3911912/11171653/00a1481c-8baa-11e5-9787-84a5450a0541.png)
![screen shot 2015-11-15 at 2 28 37 pm](https://cloud.githubusercontent.com/assets/3911912/11171652/00a13b10-8baa-11e5-9f1e-da1664f45b8f.png)
__After__
![screen shot 2015-11-15 at 2 27 48 pm](https://cloud.githubusercontent.com/assets/3911912/11171651/009ee022-8baa-11e5-9e20-440e73808da4.png)

so, we see that after the change, the point with `value = null` appears first but before the change, the `null` value was the last point. While we wouldn't think the position of the null value matters, it turns out to be very important. This brings us to highcharts.

#### Highcharts
highcharts really, really hates `nulls` in column charts as the first `x` value. In [this JSFiddle](https://jsfiddle.net/Ly6voa3h/4/) we see that an empty chart is rendered when the first data point has `null` as the first `x` value. I am not sure why this breaks highcharts but it does as evidenced in that JSFiddle. [This JSFiddle](https://jsfiddle.net/8fszqmjj/3/) shows that the chart behaves just fine so long as the `null` is any other data point. 

I'll put together a PR for this but I think the simplest fix is just to replace `null` with `''` and let highcharts sort it out from there. [Here's a JSFiddle](https://jsfiddle.net/1jpg25pq/3/) showing that behavior with `null ==> ''` replacement..

**Comment by bruth** [comment]
That was a pretty epic evaluation. Thanks for digging into it.

**Comment by naegelyd** [comment]
> That was a pretty epic evaluation. Thanks for digging into it.
